trigger:
- master
- develop

steps:
- script: |
    dotnet restore
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    msbuildArgs: '/m'
    platform: 'x64'
    configuration: 'Release'
    msbuildArchitecture: 'x64'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
