pool:
  vmImage: 'windows-latest'
  
trigger:
- master
- develop

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.0.100-preview8-013656'
    includePreviewVersions: true
- task: NuGetToolInstaller@1
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    verbosityRestore: 'Normal'
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    msbuildArgs: '/t:Build,Publish'
    platform: 'x64'
    configuration: 'Release'
    clean: true
    maximumCpuCount: true
    msbuildArchitecture: 'x64'
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    platform: 'x64'
    configuration: 'Release'
- task: ArchiveFiles@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    rootFolderOrFile: 'hjudge.JudgeHost/src/bin/Release/netcoreapp3.0/publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/hjudge.JudgeHost.zip'
    replaceExistingArchive: true
- task: ArchiveFiles@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    rootFolderOrFile: 'hjudge.FileHost/src/bin/Release/netcoreapp3.0/publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/hjudge.FileHost.zip'
    replaceExistingArchive: true
- task: ArchiveFiles@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    rootFolderOrFile: 'hjudge.WebHost/src/bin/Release/netcoreapp3.0/publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/hjudge.WebHost.zip'
    replaceExistingArchive: true
- task: ArchiveFiles@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    rootFolderOrFile: 'x64/Release'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/hjudge.Exec.Windows.zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'hjudge_artifacts_$(Build.BuildId)'